services:
  - type: web
    name: trading-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run ui/monitor.py --server.port=10000 --server.enableCORS=false